### ISSUE TITLE
执行mvn时报错

### ISSUE THREAD

**Issue by yileye** [baidu/BIPlatform#10]
[ERROR] Failed to execute goal on project designer: Could not resolve dependencies for project com.baidu.rigel.biplatform:designer:jar:2.0.0-SNAPSHOT: The following artifacts could not be resolved: com.baidu.rigel.biplatform:cache:jar:2.0.0-SNAPSHOT, com.baidu.rigel.biplatform:schedule:jar:2.0.0-SNAPSHOT, com.baidu.rigel.biplatform:common-api:jar:2.0.0-SNAPSHOT, com.baidu.rigel.biplatform:model:jar:2.0.0-SNAPSHOT: Could not find artifact com.baidu.rigel.biplatform:cache:jar:2.0.0-SNAPSHOT

**Comment by wangyuxue** [comment]
你好，构建项目需要maven的版本在3以上，在build之前，先clean一下。

**Comment by herocsl** [comment]
maven 3.5.0，mvn clean install 亦然报错如上 @wangyuxue

**Comment by basebase** [comment]
请问下，你们找到了解决方法了吗？我也遇到了

**Comment by jiang4yu** [comment]
@basebase @wangyuxue 
这个报错的原因是本地没有 cache、common-api等相关依赖包；解决方法有如下两种：
- 1、可以先对每一个模块进行一次 mvn install 后，再分别在fileserver、tesseract、designer目录；
- 2、直接在biplatform 目录下进行统一的 mvn install
