### ISSUE TITLE
部署成功后，登陆的用户名和密码多少？

### ISSUE THREAD

**Issue by blue20080** [baidu/BIPlatform#13]
用户名貌似是：github
密码是加密的，看不出来。
使用demo/demo无法登陆。

**Comment by wangyuxue** [comment]
你部署的哪个版本？

**Comment by blue20080** [comment]
目前github上最新的版本

**Comment by wangyuxue** [comment]
@blue20080 可以自己注册用户，注册之后，会收到邮件。自己开通就可以了

**Comment by blue20080** [comment]
@wangyuxue  谢谢！ 那需要配置邮件地址到自己到邮箱吧？我试一下。

**Comment by wangyuxue** [comment]
@blue20080 可以的

**Comment by lanfeiyung** [comment]
部署最新版本后，注册一直提示
![image](https://user-images.githubusercontent.com/32693605/43452635-7f3ef22c-94ea-11e8-8d86-72391f278101.png)
后台打印
![image](https://user-images.githubusercontent.com/32693605/43452741-c6b8015c-94ea-11e8-8fd5-4db842572d69.png)
