### ISSUE TITLE
配置维度的时候报错

### ISSUE THREAD

**Issue by czp11210** [baidu/BIPlatform#15]
<img width="595" alt="image" src="https://user-images.githubusercontent.com/5218539/40977259-0736a6ac-6903-11e8-9419-ef138ec6ec50.png">

<img width="960" alt="image" src="https://user-images.githubusercontent.com/5218539/40977229-f4ac4c8a-6902-11e8-8fcb-58d5db7c4e06.png">

在调试源码过程中缺失类文件com.baidu.rigel.biplatform.queryrouter.handle.manager.security.SecurityFilter
配置文件ac.properties里缺失配置项server.queryrouter.systemcode、server.queryrouter.systemkey

上述缺失烦请作者补充，期待回复，感谢！

**Comment by wangyuxue** [comment]
server.queryrouter.systemcode=biplatform
server.queryrouter.systemkey=biplatform

@czp11210  这个属性值可以自己配置，以上是示例

**Comment by czp11210** [comment]
感谢回复！这个类源文件能否给我，谢谢！
com.baidu.rigel.biplatform.queryrouter.handle.manager.security.SecurityFilter
