### ISSUE TITLE
什么时候可以提供完整版代码?

### ISSUE THREAD

**Issue by suncf1985** [baidu/BIPlatform#2]
这版是不完全开源?

可否提供详细的配置文件及整体架构图
现在的代码应该是2.0了吧.对应的文档还没有更新呢..
windows服务器目前也是不支持的吧?

**Comment by wangyuxue** [comment]
@suncf1985 你好，项目是用java语言开发的，没有平台的限制。启动服务是基于shell脚本开发的。启动可以通过java -jar的形式启动
