### ISSUE TITLE
当前版本部署后，注册不了

### ISSUE THREAD

**Issue by lanfeiyung** [baidu/BIPlatform#21]
如题，
前台报错
![image](https://user-images.githubusercontent.com/32693605/43571259-1681e5ec-966f-11e8-8b7d-2ef902b8d122.png)
后台报错
![image](https://user-images.githubusercontent.com/32693605/43571276-232e5cf8-966f-11e8-8f32-434d4a9e82c1.png)
application.properties配置修改如下：
![image](https://user-images.githubusercontent.com/32693605/43571313-420fc2d8-966f-11e8-8b85-49a4e2450344.png)

**Comment by wangyuxue** [comment]
这里需要检查一下发送邮件的邮箱账号、密码是否正确。
