### ISSUE TITLE
运行fileserver报错

### ISSUE THREAD

**Issue by ganyechuan** [baidu/BIPlatform#4]
fileserver：
1）mvn install
2）java -jar fileserver-2.0.0-SNAPSHOT.jar
报如下错误，解开fileserver-2.0.0-SNAPSHOT.jar包，里边没有lib目录
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 0
        at com.baidu.rigel.biplatform.ma.file.serv.FileServer.main(FileServer.java:155)

**Comment by wangyuxue** [comment]
请先看一下手册，检查一下配置文件
